title: "Jorge Esteban Ramírez Sashida"
author: "Jorge Esteban Ramírez Sashida"
description: "Data Scientist · Music + Machine Learning"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "About", file: "about.md"}
  - {title: "Work", file: "work.md"}
  - {title: "Blog", file: "blog.md"}
  - {title: "CV", url: "/assets/MyCV_JorgeEstebanRamirezSashida.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Spotify, icon: spotify, url: "https://open.spotify.com/user/esteban.ramirezsashida?si=01004f844f314c84"}
  - {title: Tidal, icon: music, url: "https://tidal.com/@cachorrohumano"}
  - {title: Last.fm, icon: headphones, url: "https://www.last.fm/user/jestebanrs"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/elcachorrohumano/"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/jorge-esteban-ramirez-sashida-26a80129a"}
  - {title: Github, icon: github, url: "https://github.com/elcachorrohumano"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
